### ISSUE TITLE
Page "Liste des centres" | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#21]
- [x] Titre de la page : Afficher seulement "Centres"
- [x] Sous-titre de la page : Afficher le nombre de centres présents dans la RECHERCHE en dessous (donc pas toujours 61)
- [x] Ajouter une colonne "Nom du centre"
- [x] Sur la première colonne : ajouter l'en-tête "Code unité"
- [x] Contenu de la colonne "Code unité" : préserver l'espace (ex : UMS 828)
- [x] Contenu de la colonne "Code unité" : tout mettre en majuscule
- [x] Dernière colonne : ajouter l'en-tête "Action"
- [x] Réordonner les colonnes : 1. Acronyme, 2. Nom complet, 3. Code unité, 4. Action
- [x] Nom des colonnes : mettre la première lettre en majuscule
- [x] Colonne Logo : Donner à tous les logos une largeur maximale de 80px
- [x] Colonne Logo : Harmoniser la hauteur des lignes
- [x] Liste des colonnes filtrables : acronyme, nom du centre, code unité
- [x] Liste des colonnes triables : acronyme, nom du centre
- [x] Par défaut, trier les résultats sur la colonne acronyme

**Comment by Delapouite** [comment]
Quelques remarques:

- Aussi surprenant cela puisse paraitre, mongo ne sauvegardait pas encore le nom du centre. Donc il faut remettre à jour la base via `node bin/populate-mongo-db.js clear`. **Attention, ça vient écraser la collection**, donc on peut se le permettre que dans ces phases initiales du dev.
- Les logos ayant des tas de tailles différentes, j'ai fait au mieux pour qu'ils ne soient ni envahissants, ni déformés.

**Comment by annelhote** [comment]
Ok, vu.

**Comment by MG95SP** [comment]
- [ ] Sous-titre de la page "Centre" : mettre "45 résultats / 61 centres" "x résultats /  x centres"
- [ ] Colonnes triables : permettre le tri dans les 2 sens (ascendant et descendant).
- [ ] Colonnes triables : rendre visible les colonnes triables.

**Comment by MG95SP** [comment]
- [ ] Rendre visible le fait qu'une colonne soit triable
- [ ] Par défaut le tri doit être fait par la colonne "acronyme" dans le sens alphabétique croissant.
