### ISSUE TITLE
data export BO -> FO

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#22]
Si je "cache" un centre dans le BO, il s'affiche toujours dans le FO.
Je ne sais pas si cette fonction a déjà été mise en place.

**Comment by Delapouite** [comment]
En l'état c'est "normal". Le BO et le FO ne sont toujours pas reliés.

**Comment by annelhote** [comment]
Ok, merci. Je supprime le milestone ainsi que le label et l'assignee de ce bug mais le garde ouvert pour tester cela en temps voulu.

**Comment by Delapouite** [comment]
FO et BO sont désormais reliés.
```js
// /app/services/data.services.js
$http.get(`${backOfficeBaseUrl}/api/export`)
```
et equivalent pour les metadata avec schema.json
