### ISSUE TITLE
Page "Modification d'un centre existant" | Onglet "Description" | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#23]
- [x] Champ "Nom complet" : manquant
- [x] Champ "Etablissements de rattachement" : champ multi-valué donc mettre une valeur par champ, pouvoir ajouter un champ à la fin, pouvoir réordonner les champs, pouvoir supprimer un champ.
- [x] Champ "Directeur" : non renseigné
- [x] Champ "Courriel Direction" : Est-ce qu'on peut mettre une validation pour un email ?
- [x] Champ "CNRS" : à masquer
- [x] Champ "MENESR" : à masquer
- [x] Champ "Historique" : Afficher un texte long et non un input d'une seule ligne

**Comment by MG95SP** [comment]
- [ ] Champ "Site web" non obligatoire.
