### ISSUE TITLE
Page "Modification d'un centre existant" | Onglet "Ecoles doctorales" | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#24]
- [x] Mettre en place un sous-formulaire pour chaque école doctorale avec les champs :
   - Numéro
   - Intitulé
   - Directeur
   - Courriel
- [x] Ce formulaire est multi-valué donc je dois pouvoir ajouter une nouvelle école doctorale, supprimer une école doctorale et réordonner les écoles doctorales.
- [x] Champ "Courriel de l'Ecole doctorale" : est-ce possible de mettre une validation email ?
- [x] Champ "Nombre de thèses soutenues en 2015" : Revoir le libellé "Nombre de thèses soutenues en **2016**"

**Comment by MG95SP** [comment]
Non validation du champ "Courriel de l'Ecole doctorale" doit être bloquant lors de la sauvegarde. Possibilité d'afficher un message d'erreur en haut du formulaire?

**Comment by Delapouite** [comment]
La validation des champs a été implémentée (requis, email, numerique).
Un message d'erreur est affiche près de chaque champ défaillant ainsi qu'un message général en haut de formulaire. Les boutons de soumissions sont bloqués tant qu'il reste des erreurs.

**Comment by MG95SP** [comment]
Ok merci!
