### ISSUE TITLE
Page "Modification d'un centre existant" | Général | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#25]
- [x] Titre de la page : acronyme du centre
- [x] Le loader continue de charger indéfiniment
- [x] Traduire le bouton "Save" par "Enregistrer"
- [x] Quelle est la méthode de sauvegarde, est-ce continue ou au clique ? Je suis sur un onglet 1, je modifie un champ, je clique sur un onglet 2, je modifie un autre champ, je sauvegarde. On est d'accord que les 2 champs modifiés sont sauvegardés ?
- [x] Où est le bouton pour ajouter un nouveau centre ?
- [x] Ces modifications ne sont pas validables http://localhost:42000/modifications

**Comment by Delapouite** [comment]
L'ajout d'un nouveau centre est encore un peu fragile. C'est principalement à cause de la génération de l'id unique que ça coince. Ce dernier se base actuellement sur le `code` (UMRtruc). Il faut donc obligatoirement le renseigner. De meme les champs complexes comme les écoles doctorales ne marchent pas encore à la création (mais ils doivent etre OK pour l'edition).

**Comment by MG95SP** [comment]
- [ ] Si le centre n'a pas d'acronyme, afficher le nom complet du centre en titre de page.
