### ISSUE TITLE
Page "Modification d'un centre existant" | Onglet "Thématique" | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#26]
- [x] Champ "Sections CNRS" : Checklist (cf. commentaire ci-dessous)
- [x] Champ "Science Politique comme discipline principale / Science Politique comme discipline secondaire" : à supprimer
- [x] Champ "Discipline principale" : à supprimer
- [x] Champ "Disciplines secondaires" : à supprimer
- [x] Champ "Mots-clés sujet" : non renseigné
- [x] Champ "Axes de recherche" : afficher une hiérarchie comme dans le FO (cf. UMR 5115). En markdown éditable ? Solution technique à trouver.
- [x] Champ "Contrats de recherche" : afficher en liste (markdown ?)
- [x] Champ "Séminaires de recherche" : afficher en liste (markdown ?)
- [x] Champ "Collaborations / réseaux" : afficher en liste (markdown ?)

**Comment by annelhote** [comment]
Champ "Sections CNRS" :
- 19 Système Terre : enveloppes superficielles
- 31 Hommes et milieux : évolution, interactions
- 32 Mondes anciens et médiévaux
- 33 Mondes modernes et contemporains
- 34 Sciences du langage
- 35 Sciences philosophiques et philologiques, sciences de l'art
- 36 Sociologie et sciences du droit
- 37 Economie et gestion
- 38 Anthropologie et étude comparative des sociétés contemporaines
- 39 Espaces, territoires et sociétés
- 40 Politique, pouvoir, organisation

**Comment by MG95SP** [comment]
Ok merci!
