### ISSUE TITLE
Page "Modification d'un centre existant" | Onglet "Documentation" | Présentation

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#28]
- [x] Champ "Archivage des données de la recherche" (le second) : renommer en "Archivage des données de la recherche **- Description**"
- [x] Champ "Archivage des données de la recherche - Description" : Est-ce possible de rendre ce champ inaccessible tant que le champ "Archivage des données de la recherche" n'est pas coché ?
- [x] Champ "Archivage des données de la recherche" : déplacer dans l'onglet "Publications"
- [x] Champ "Archivage des données de la recherche - Description" : déplacer dans l'onglet "Publications"
- [x] Champ "Valorisation des publications par le laboratoire" : déplacer dans l'onglet "Publications"
- [x] Champ "Centre de documentation ou bibliothèque en propre" (le second) : renommer en "Centre de documentation ou bibliothèque en propre **- Description**"

**Comment by MG95SP** [comment]
- [ ] Champ "Centre de documentation ou bibliothèque en propre - Description" : Afficher si le champ "Centre de documentation ou bibliothèque en propre ?" est coché. 
- [ ] Champ "Centre de documentation ou bibliothèque en propre - Description" : le passer en markdown.
- [ ] Champ "Site Web" : Afficher si le champ ""Centre de documentation ou bibliothèque en propre ?" est coché. 
- [ ] Champ "Site Web" : renommer "Site web du centre de documentation"

**Comment by MG95SP** [comment]
Ok merci!
