### ISSUE TITLE
FrontOffice | Onglet "Données" | Colonne "Intitulé"

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#32]
Cette première colonne est vide !

**Comment by annelhote** [comment]
Attention, cet intitulé a été perdu sur la liste complète des contres ainsi que sur la vue "carto" des centres.

![github_01](https://user-images.githubusercontent.com/1478919/34945375-6e126df8-fa03-11e7-99c6-10e197cb5241.png)

![github_02](https://user-images.githubusercontent.com/1478919/34945384-7757ac2a-fa03-11e7-91aa-2f26c3704cd0.png)

**Comment by naholyr** [comment]
Je n'ai pas l'impression de le reproduire, mais sur le dernier screenshot je ne vois pas quelle donnée manque donc j'ai peut-être besoin de plus d'infos.
