### ISSUE TITLE
Gestion du logo dans le formulaire

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#45]
Pouvoir modifier le logo dans le formulaire, onglet "Description".

**Comment by Delapouite** [comment]
La gestion d'upload de données binaires est toujours un sujet compliqué.

Dans le cadre de cette application cela se complique encore d'avantage de part la concurrence potentielle entre plusieurs modifications pointant vers le meme fichier.

Ainsi, en prenant en compte un certain pragmatisme et le temps alloué à cette tache complexe voici l'etat actuel du commit plus haut:

- Seuls les admins peuvent changer le logo d'un centre (opération rare)
- Cela se passe via un formulaire autonome pour ne pas s'empetrer dans le systeme de diff / validation.
- Le bouton d'accès se fait dans la colonne "actions" de la liste des centres.
- Lors du choix du fichier, une prévisualisation se fait coté client.
- Le fichier n'est transmis que lors de l'appui sur le bouton vert.
- L'image est renommé et vient se placer dans le dossier actuel `/img/logos_centres_de_recherche_jpeg/${acronym}.jpeg`.
- Suivant l'archi Docker et les volumes partagés entre `bo` et `fo` il faudra donc sans doute convenir d'une autre strategie de partage des images entre les 2 containers.

**Comment by annelhote** [comment]
Bonne remarque de @jri-sp quid de la construction de l'image Docker. A priori dans ce cas, les modifications des logos sont-elles prises en compte ?

**Comment by jri-sp** [comment]
Il faudrait probablement un troisième volume docker pour les médias de l'application. Sinon à chaque mise à jour d'image on perd les données uploadées.

**Comment by MG95SP** [comment]
Impossibilité de transmettre le logo. Rien ne se déclenche lorsque l'on clique sur "transmettre" 
![logo](https://user-images.githubusercontent.com/35340064/42820597-cdff6ab4-89d6-11e8-8d4b-2ba39a62315b.JPG)

**Comment by MG95SP** [comment]
Test avec 4ko, 6ko et 70Ko =même message d’erreur :
![erreur logo](https://user-images.githubusercontent.com/35340064/43454524-a8ea8618-94bd-11e8-9099-b62ebaf0bd0f.JPG)

**Comment by Delapouite** [comment]
Ce message est un peu barbare. Je viens de le simplifier.
On risque d'obtenir le plus simple "Can't move file"
Si c'est le cas, il va falloir voir avec Jeremy pour que le container docker puisse écrire d'une manière ou d'une autre dans le dossier souhaité.

**Comment by naholyr** [comment]
À voir avec @jri-sp : vérifier l'utilisateur, et surtout ses permissions, qui fait l'upload sur le volume correspondant.

**Comment by naholyr** [comment]
- OK en dév
- À voir en preprod après la mise en place du volume

**Comment by MG95SP** [comment]
Ok en prod
