### ISSUE TITLE
Reprendre la signature du mail

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#46]
Contenu de cette signature à formuler par @MG95SP .

**Comment by Delapouite** [comment]
Dans les fichiers toml de `/config` il est maintenant possible de modifier:
- `mailer.subject`: prefix qui est utilisé devant le titre de tous les emails
- `mailer.signature`: une ligne qui est ajouté dans le pied de tous les emails.

**Comment by MG95SP** [comment]
Les textes sont bons.
- Il faut simplement ajouter dans la signature : L'équipe "Cartographie de la science politique"
- Et modifier dans l'objet des mails [Carto Science Po] par [Carto ScPo]
