### ISSUE TITLE
mettre le baseurl en conf

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#47]
Setter une variable de configuration qui contient la baseurl puis la remplacer dans index.html et gérer les conséquences (nouvelles urls sur les onglets).

**Comment by Delapouite** [comment]
Dans un precedent échange, Sylvain proposait de faire un `sed` sur le fichier `index.html` du bo pour remplacer le `href` de la balise `<base>` qui pose soucis au router d'angular. J'ai opté pour une variante de cette approche dans le commit ci dessus. C'est le serveur node qui se charge de remplacer le `href` à la volée suivant la config.
Il s'agit d'une nouvelle valeur explicite `baseHref` qui ne se focalise que sur ce remplacement.

**Comment by jri-sp** [comment]
Je réouvre l'issue car la modif avec cette nouvelle variable fonctionne bien mais le problème maintenant c'est que tout les liens des menus, et les les appels à l'API (pour la session par exemple) se font toujours sur avec `/` comme base, donc on a des 404:
<img width="960" alt="capture d ecran 2018-03-30 a 14 40 03" src="https://user-images.githubusercontent.com/5879903/38137968-453a6c82-3428-11e8-9751-a5c4023503b9.png">

**Comment by Delapouite** [comment]
Voici les modifs apportées dans ce commit : https://github.com/SciencesPoDRIS/CartoScPo/commit/18a39d9c06f1ed7726121235f929e0db060908e4

- Les appels XHR vers l'API passent désormais tous via un nouveau service angular.js, sorte de wrapper autour de `$http`. Dans ce nouveau service `api.js`, les appels se font en URL relatives qui doivent donc respecter la valeur de `<base href="/admin/>`.
Autrement dit:
`api.get('centers')` fait un appel vers `/admin/api/center`.
- les liens (`<a href="foo">`) sont maintenant eux aussi en relatifs pour se baser sur `<base>`.

Afin de tester que tout fonctionnait correctement, j'ai reproduis sur mon poste de dev une condition où le BO est servi via `nginx` sur l'adresse `carto.localhost/admin`

La modif semble etre bonne aussi pour le lancement via docker.

**Comment by annelhote** [comment]
En PPRD, après authentification en tant qu'admin, les liens vers "Modifications" et "Utilisateurs" ne fonctionnent plus. Le clic redirige vers la homepage du backoffice avec déconnection.

**Comment by Delapouite** [comment]
Après un bon grattage de tête je pense avoir mis le doigt sur ce qui flanche d'après les symptômes.

Le login en tant qu'admin semble bien se dérouler, mais la session quant à elle n'est pas enregistrée (pas de cookie, donc pas d'ID). Si bien qu'au prochain lien navigué, on se fait kicker par le serveur.

C'est Redis qui est en charge de conserver les sessions. Donc je suspecte que c'est le point défaillant du système.

Et en effet, en faisant exprès de démarrer le serveur node sans que le serveur Redis soit lui meme démarrer, je reproduis un scenario similaire.

Ce qui est assez troublant c'est le crash silencieux de Redis. Autrement dit l'application node démarre tout de même alors qu'il lui manque un morceau primordial.

Ainsi, dans https://github.com/SciencesPoDRIS/CartoScPo/commit/e88b446a62414bbc447e4935d004d4200bcd0803 j'ai activé le log d'erreurs pour redis.

On devrait voir passer des messages d'erreurs du style:
```
 redis Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
  redis     at Object._errnoException (util.js:1024:11)
  redis     at _exceptionWithHostPort (util.js:1046:20)
  redis     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) +0ms
```
Ces logs utilisent https://www.npmjs.com/package/debug donc pour les voir il faut lancer

```DEBUG=redis node index.js```

De plus, le login d'un utilisateur devrait désormais être impossible et résulter en une erreur 503 renvoyée au client angularjs. En inspectant la réponse à `POST /login` dans l'onglet network du devtools, on devrait avoir un "redis not connected".

Si c'est bien ça, alors il reste à mettre le doigt sur le sujet de fond: pourquoi node n'arrive pas à se connecter à Redis (un port docker fermé?).

**Comment by jri-sp** [comment]
Merci pour l'analyse! en effet j'avais oublié de mettre le lien entre le back-office et redis, je suis désolé...
C'est réparé dans mon dernier commit (3794550691c3ca874a669546fa13fe92b141ba94), et c'est passé en préproduction. 
Ça fonctionne mieux maintenant !

**Comment by annelhote** [comment]
Merci ! 5 minutes avant ma réunion. Vous êtes 🎉 🎊 🔮 💖 🌈
