### ISSUE TITLE
Erreur Angular FO

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#48]
Erreur Angular en FO : 
Error: $injector:modulerr
Module Error
Failed to instantiate module bib due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.6.10/$injector/modulerr?p0=...)
(...)

Suite à modification d'un centre.

**Comment by annelhote** [comment]
Voici les modifications qui ont provoquées cette erreur (a priori) :

<img width="1338" alt="screen shot 2018-05-18 at 11 12 00" src="https://user-images.githubusercontent.com/1478919/40226585-59cbca9e-5a8c-11e8-8f17-042b88d99ea7.png">

**Comment by annelhote** [comment]
"Pour diagnostiquer ce qui se passe, j'aurais besoin de l'erreur complète, autrement dit ce qui est ellipsé dans le message ci dessus.
Est il possible de me transmettre ça via mail ou meme capture d'ecran ?"

**Comment by MG95SP** [comment]
Le FO en prod ne fait apparaître que 18 centres de recherche. Avec des bugs d'affichage, comme après la date de MAJ du centre :
![captureboaffichage](https://user-images.githubusercontent.com/35340064/40547623-bb9f8dae-6032-11e8-9c71-910bf861f194.JPG)
