### ISSUE TITLE
Mise en prod | No more modifications or users

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#52]
Après mise en prod aujourd'hui vers midi par @jri-sp , plus aucune modification listée dans l'onglet dédié du BO, ni même d'utilisateur...

https://cartosciencepolitique.sciencespo.fr/bo/users

Error 403 (Forbidden)

<img width="710" alt="screen shot 2018-05-23 at 15 19 59" src="https://user-images.githubusercontent.com/1478919/40427036-d86ef254-5e9c-11e8-9927-3213a3012a6b.png">

**Comment by annelhote** [comment]
Lié à ce commit :
https://github.com/SciencesPoDRIS/CartoScPo/commit/ef479ef3e011e477a79ba878fc25ba02eb33d480

**Comment by Delapouite** [comment]
Non ce commit n'est pas lié.

Je suis totalement dans le flou. Après plusieurs heures de recherche je suis toujours coincé.
- pas de soucis avec mon installation de dev ad hoc.
- pas de soucis en lançant l'environnement de prod sur ma machine avec:
```docker-compose -f docker-compose.prod.yml up```

aussi bien avec les images du hub que des images fraichement buildées en local.

J'ai aussi fait le test en faisant un checkout du commit https://github.com/SciencesPoDRIS/CartoScPo/commit/3794550691c3ca874a669546fa13fe92b141ba94 en eliminant donc tout le code modifié depuis.

Faute de mieux, afind d'y voir plus clair je viens de soumettre un log temporaire: https://github.com/SciencesPoDRIS/CartoScPo/commit/595e05aa305ed72c3c8da02090b892442a8a39e7

De cette manière on devra avoir plus de grain à moudre en analysant la requete une fois que ce commit sera déployé sur la prod.

**Comment by annelhote** [comment]
Finalement lié à une conf de @jri-sp qui l'a fix puis a relivré en préprod et en prod :(
