### ISSUE TITLE
Apparition de modifications non-sollicitées

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#53]
- Lors d'une demande de modification par un admin sur les champs "code unité" et "l'historiques", cela a occasionné la disparition du centre concerné sur le FO. Lorsque l'on affiche la modif, un champs non demandé en modif (Masqué sur le Front Office ?) est passé de "true" à "nul"
![capturebugurmis](https://user-images.githubusercontent.com/35340064/40550804-74cf3952-603b-11e8-8d62-d538c13c0ab7.JPG)
-La modification du bug décrit ci-dessus sur le champ "Masqué sur le Front Office ?" a permis au centre de réapparaître sur le BO en conservant les modifs pertinentes précédentes. Mais affiche en BO dans "modifications" que le champ "Masqué sur le Front Office ? - modification" est passé de "true" à "false"
![capturebugurmis_2](https://user-images.githubusercontent.com/35340064/40550940-d6e8d8a0-603b-11e8-858f-dfe0c8046818.JPG)
- Un bug similaire sur un champ de modif non-sollicité est également apparu sur le champ "historique" 
![image](https://user-images.githubusercontent.com/35340064/40550986-07d0d1fc-603c-11e8-9fb4-645770cbfdb0.png)

**Comment by Delapouite** [comment]
2 problèmes distincts résolus dans les commits ci dessus:
- le champ Masqué sur le Front Office ? (qui s'appelle 'hidden' dans schema.json) est de type boolean met restait à `null` lors de la phase d'import. Il est désormais forcé à `false`.
- le problème d'espace apparaissant/disparaissant dans les champs markdown vient du fait que les data d'origine contenaient un joyeux melange de `\r\n` et `\n`. Tout est désormais harmoniser à `\n` durant l'import initial.
