### ISSUE TITLE
Bugs d' affichage de certaines données sur le FO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#56]
Certaines données des onglets "Publication" ou "Documentation" qui sont correctes dans le BO ne s'affichent pas ou s'affichent dans les mauvais champs sur le FO.
Exemples : 
- Sans effectuer aucune demande de modif, pour le CEE le champ "Publications versées dans HAL ?" à l'onglet "publication" indique "true" au lieu de "oui" malgré qu'il soit coché dans le BO. Idem pour "Publications versées dans un dépôt institutionnel ?" qui n'affiche rien alors qu'il est coché.
![image](https://user-images.githubusercontent.com/35340064/40551841-55745b34-603e-11e8-9ddf-79eeff666306.png)
-  Idem à l'onglet "documentation". N'affiche pas les bibliothèques utilisées (pourtant reseigné dans le BO) et affiche les données relatives aux "Préconisations pour le dépôt en open access des publications" à la rubrique "offre de formations documentaires"
![image](https://user-images.githubusercontent.com/35340064/40552061-f8e919f8-603e-11e8-85f2-f3ee9c3dda3b.png)
- Idem lors de la création d'un nouveau centre TEST (supprimé depuis), Le champ "bibliothèques utilisées" à l'onglet "documentation" ne s'affiche pas sur le FO alors qu'il est bien renseigné en BO

**Comment by MG95SP** [comment]
Un problème d'affichage se produit également à l'onglet "description" pour le champ "site web"

**Comment by Delapouite** [comment]
Concernant le dernier point soulevé, le **site web de l'onglet description**:

Dans mon jeu de donnée local j'ai par exemple le `CADIS` qui n'a aucune valeur et le `CED` qui en a une.
Visuellement sur le Front End, le lien vers le site s'affiche bien pour le CED, mais pour le CADIS c'est un peu perturbant car on a juste l'icone du globe terrestre et rien à coté.

S'agit il d'un cas similaire sur lequel tu es tombé ?

Afin d'éviter d'afficher un globe terrestre vide, je le masque dans ce nouveau commit: https://github.com/SciencesPoDRIS/CartoScPo/commit/7abcf5f22298e3fc5464fa87837c69dec742fda8 (qui sera déployé plus tard)

**Comment by MG95SP** [comment]
Le problème d'affichage des données a été corrigé à peu près partout sauf pour l'item “revues en propre” à l’onglet “publications” et pour l'item "Mots-clés sujet" à l’onglet “thématiques”.
Exemple avec le LAM

**Comment by Delapouite** [comment]
Les deux champs mentionnés ont été corrigés.

**Comment by naholyr** [comment]
À noter : certains des problèmes liées à cette issue sont a priori en réalité liées à la #61

**Comment by naholyr** [comment]
- Corrigé en dev & preprod
- Reste-t-il des choses à modifier en pprd ?

**Comment by MG95SP** [comment]
Résolu en pprd. Sauf "Archivage des données de la recherche" qui s'était décoché en BO (même lorsque le champ était renseigné) et qui n'apparait donc pas en FO.
Si cela peut aider à résoudre le bug, possibilité de rendre ce champs toujours visible en FO et BO (sans avoir à le cocher).
![image](https://user-images.githubusercontent.com/35340064/50787124-d8f7a680-12b5-11e9-84eb-dcae17883878.png)

**Comment by naholyr** [comment]
Étrangement en local j'ai reproduit ce problème une fois seulement, puis en relançant le process "back-office" il semble être *parti tout seul* :confused: 
Il n'y a pas de spécificité sur ce champ par rapport aux autres "boolean-item" (incluant également "Centre de documentation ou bibliothèque en propre", "Collections auprès d'éditeurs", "Revues en propre").

**En préprod est-ce que ces 4 champs buggent de manière équivalentes ou c'est juste celui-là ?**

Vu le comportement en local, je pense qu'une des deux actions suivantes a corrigé le bug :

- Redémarrer le process "back-office", dans ce cas c'est peut-être simplement les assets du back-office (angular) qui doivent être rebuildés
- Effectuer une modification sur un des autres champs, dans ce cas c'est peut-être une corruption des données (mais j'en doute car en modifier un seul centre ça n'aurait pas corrigé les autres).

Je push simplement le template remis en forme automatiquement par mon éditeur, il faudrait **essayer de reconstruire l'image** pour s'assurer que le back-office est bien relancé et recompilé. On verra si ça suffit en réalité.

**Comment by MG95SP** [comment]
Il n'y a que le champ "Archivage des données de la recherche" qui pose problème - et pour un seul centre. Je te confirme qu'en pprd ce champ est toujours décoché avec le CEE mais ok avec le CEVIPOF, le CERAPS, et les autres centres qui ont une valeur pour cet item !
Le problème portait peut-être que sur le CEE ??

**Comment by naholyr** [comment]
Dans le doute, pour info j'ai annulé le commit c5bdb59 dans le cadre de la #70, à voir si le bug présent ici se reproduit du coup.

> Le problème portait peut-être que sur le CEE ??

Est-ce toujours le cas ?
