### ISSUE TITLE
Suppression de centre impossible en BO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#58]
La suppression d'un centre est proposée mais même après validation de la fenêtre pop-up de confirmation elle est impossible à valider.
![suppression](https://user-images.githubusercontent.com/35340064/42820233-eae2d09a-89d5-11e8-8b5b-147abd6ccc4c.JPG)

**Comment by MG95SP** [comment]
Après vérification demandée, e problème persiste à la fois sur un centre nouvellement créé et sur les centres existants.

**Comment by Delapouite** [comment]
Je comprends pas ce qui coince. Je viens de me connecter sur la prod et supprimer le Medialab sans soucis.
Il n'y a bien plus que 92 centres sur le FO et le BO.
