### ISSUE TITLE
header

### ISSUE THREAD

**Issue by annelhote** [SciencesPoDRIS/CartoScPo#6]
* Logo bib aligné à droite
* Menu aligné à gauche : Accueil (logo d'une maison), "Cartographie de la Science Politique en France" , "le projet", "l'équipe"

**Comment by Delapouite** [comment]
Fait sur la branche `dev`.

Pour le moment le lien Cartographie de la Science Politique en France pointe vers un placeholder le temps d'extraire l'outil de la page d'accueil.

De même le lien équipe pointe vers un template à remplir à posteriori.
