### ISSUE TITLE
Problème d'affichage de la mise en forme markdown

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#61]
Il existe une différence d'affichage entre la Prévisualisation Markdown du BO et ce qui est affiché sur le FO. Surtout en ce qui concerne les listes hiérarchisées.
Exemple avec l'item "axes de recherche" à l'onglet "thématiques" pour le LAM (mais le problème est repérable également sur le même onglet à l'item "collaboration réseaux" ou sur l'onglet "documentation" à l'item "Ressources numériques à disposition des chercheurs").
BO : 
![lam bo](https://user-images.githubusercontent.com/35340064/43455489-57a43e22-94c0-11e8-9200-d264b7794d64.JPG)
FO : 
![lam fo](https://user-images.githubusercontent.com/35340064/43455537-7c5f35e6-94c0-11e8-937f-a57630ec36a3.JPG)

**Comment by Delapouite** [comment]
Le BO et FO utilisent maintenant le meme renderer (commonmark) donc cette difference de rendu entre les 2 bords devraient disparaitre.

**Comment by naholyr** [comment]
Suite à la modification, le markdown n'est plus interprété côté FO (rendu tel quel)

**Comment by naholyr** [comment]
Corrigé par le commit f45a1c3 sur la branche `dev`

**Comment by naholyr** [comment]
- Corrigé en dev OK
- Déployé en preprod OK

**Comment by MG95SP** [comment]
ok en prod
