### ISSUE TITLE
Hyperlien "Fiche du centre dans ScanR" ne fonctionne pas

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#62]
Lien normalement cliquable "Fiche du centre dans ScanR" de l'onglet "description" ne fonctionne pas pour l'ensemble des centres.

**Comment by naholyr** [comment]
Ce n'est pas juste un souci d'affichage mais de données : L'info est bien présente dans le fichier ``data.json`` (chemin ``administration/Lien_ScanR``) mais pas dans la base de données Mongo, donc ni le BO ni le FO ne peuvent l'afficher, du coup il va falloir l'importer.

Je pense que ça rejoint ce dont on parlait concernant les méta-données manquantes, j'ai pris la liberté de spécifier déjà l'id dans la spreadsheet "metadata" : `scanr_url`, et de compléter le fichier ``schema.json`` ainsi que le script ``populate`` pour prendre en compte ce champ.

Localement ça corrige le problème, mais au prix d'une réinitialisation des données (exécution de ``node bin/populate-mongo-db.js --clear``).

Question : comment gérer l'ajout de cette donnée en preprod/prod sans perte de données ? Vous allez refaire la saisie manuellement ou on prévoit un script de mise à jour ?

**Comment by MG95SP** [comment]
Merci de ces précisions.
Refaire la saisie manuellement serait catastrophique, il serait mieux de
prévoir un script de mise à jour (même si j'avoue ne pas me rendre compte
de ce que cela implique). L'ensemble des modifications effectuées depuis la
mise en prod apparaissent dans le BO à l'onglet "modifications" :
https://cartosciencepolitique.sciencespo.fr/bo/modifications
Mais il faut être en admin pour le voir. Je viens de te créer un compte
admin : Mdp : Nicolascarto2018

Merci,


*Michaël Goudoux*
Bibliothécaire référent pour la Science Politique

Responsable de la bibliothèque de recherche

[image: Sciences Po]
Direction des Ressources et de l'information Scientifique
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 56 86
michael.goudoux@sciencespo.fr
www.sciencespo.fr/bibliotheque

**Comment by naholyr** [comment]
- Corrigé en dév OK
- Déployé en preprod OK

**Comment by MG95SP** [comment]
Ok en prod.
Seul problème, inverse cette fois : le lien "Fiche du centre dans ScanR" s'affiche en FO même lorsqu'il n'est pas renseigné en FO.
Exemple avec le LIEPP.

**Comment by naholyr** [comment]
Corrigé et pushé en dév, prêt pour la préprod (inclus #72)
