### ISSUE TITLE
Ne plus afficher l'item "Publications versées dans HAL ?" dans la liste des résultats

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#63]
Sur la page des centres le dernier item pour filtrer les résultats "Publications versées dans HAL ?" ne s'affiche pas clairement et n'est pas pertinent. Il est préférable de le supprimer et qu'il ne fasse plus partie des filtres.
![image](https://user-images.githubusercontent.com/35340064/48777395-be03af80-ecd2-11e8-9658-151bf3ed4743.png)

**Comment by MG95SP** [comment]
Il faudrait également réduire l’appellation de l'item "Mots-clés sujet selon l'annuaire du MENESR" en supprimant (...de l'annuaire du MENESR) en ne conservant que la mention "Mots-clés" (comme c'est déjà le cas en BO).
![image](https://user-images.githubusercontent.com/35340064/50240768-f546a880-03c5-11e9-822e-66a6e91fea8a.png)

**Comment by naholyr** [comment]
- Corrigé en dév
- Pushé (et normalement déployé) en preprod

**Comment by MG95SP** [comment]
Ok en pprd pour les modifs demandées. Mais problème sur "Section CNRS" qui désormais n'affiche plus les résultats les plus fréquents + "Ville" qui a été transformé en "Adresses"
Avant : 
![image](https://user-images.githubusercontent.com/35340064/50786743-ab5e2d80-12b4-11e9-9d6e-61d332238752.png)
En pprd : 
![image](https://user-images.githubusercontent.com/35340064/50786759-bdd86700-12b4-11e9-9a21-32fde0e2c9e8.png)
Avant : 
![image](https://user-images.githubusercontent.com/35340064/50786843-ff691200-12b4-11e9-90b7-4ef9df595488.png)
En pprd : 
![image](https://user-images.githubusercontent.com/35340064/50786871-160f6900-12b5-11e9-9b69-71ec8f5f942d.png)
Pour ces 2 points et pour ces 2 points uniquement, il faut revenir à la situation précédente.

**Comment by MG95SP** [comment]
Résolu en pprd. Vérif en prod

**Comment by MG95SP** [comment]
Ok en prod
