### ISSUE TITLE
Créer un lien page d'accueil FO vers BO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#64]
Créer le lien de la page d'accueil FO ("N’hésitez pas à contribuer") vers le BO (page "Centres") 
https://cartosciencepolitique.sciencespo.fr/bo/centers
![image](https://user-images.githubusercontent.com/35340064/50305651-c1d24f80-0493-11e9-8754-345f480e0b4b.png)

**Comment by naholyr** [comment]
- OK en dev
- Pushé en preprod

**Comment by MG95SP** [comment]
Ok en prod
