### ISSUE TITLE
Problème d'affichage du champ "Mots-clés" de l'onglet "thématiques"

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#66]
Le champ "Mots-clés" de l'onglet "thématiques" présent en BO se retrouve sur 2 champs en FO "mots clés" et "annuaire du MENESR"
![image](https://user-images.githubusercontent.com/35340064/50307194-f811ce00-0497-11e9-922b-640a668dac12.png)

De plus, les données renseignées dans ce champ en BO ne s'affichent pas en FO
Exemple avec le CASE

Normalement il s'agit d'un 1 seul item regroupé en BO et en FO sous l'intitulé "Mots-clés sujet" **(c'est cet intitulé que l'on retrouve en BO**)
![image](https://user-images.githubusercontent.com/35340064/50307676-61dea780-0499-11e9-959a-366efa15379a.png)

Problème résolu **en pprd** sauf pour l'intitulé exacte :
![image](https://user-images.githubusercontent.com/35340064/50307515-f0065e00-0498-11e9-9bb8-228c86ae8327.png)

**Comment by naholyr** [comment]
Corrigé en dév

**Comment by MG95SP** [comment]
Ok en prod
