### ISSUE TITLE
Ajout champs manquants dans le FO et le BO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#67]
Numero National de Structure
Lien RNSR
Fiche du centre dans ScanR
Wikidata
Lien Wikipedia
https://docs.google.com/spreadsheets/d/1WA_jhcnXvJzm6kJsxALKtjXcHpSU7Uh-lsKv6Nes3Jo/edit#gid=0

- Vu en BO en pprd mais à placer sous "site web du centre"
![image](https://user-images.githubusercontent.com/35340064/50341876-ede7e200-0520-11e9-9418-1ba6008989e3.png)

- En FO, il faut positionner le "Numero National de Structure" sous "Année de création"
![image](https://user-images.githubusercontent.com/35340064/50342161-39e75680-0522-11e9-8abf-bee850b19f22.png)

- En FO, les autres champs "Lien RNSR", "Wikidata" et "Lien Wikipedia" doivent être placés sous "Fiche du centre dans ScanR"
![image](https://user-images.githubusercontent.com/35340064/50342252-9480b280-0522-11e9-8ddd-3b082c4f41a0.png)

- A l'exception du "Numero National de Structure" les autres champs doivent apparaître en FO **que** s'il sont renseignés en BO.

**Comment by naholyr** [comment]
- Corrigé en dév

Note @jri-sp j'avais loupé une config dans le `schema.json` et il faudra rejouer le script de mise à jour, limité au champ "wikidata" : **`node bin/populate-mongo-db.js -u wikidata`**. Dès que j'ai fini l'issue #68 je fais un mail pour le prochain déploiement en preprod.

**Comment by MG95SP** [comment]
Ok en prod
