### ISSUE TITLE
Rendre visible en FO les champs "offre de formation documentaire" et "collaborations documentaires" même s'ils ne sont pas renseignées en BO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#68]
A l'onglet "Documentation", les champs "offre de formation documentaire" et "collaborations documentaires" n’apparaissent pas dans le FO si le champ est vide.
Il faudrait les rendre apparents dans tous les cas.
Exemple avec le CADIS
![image](https://user-images.githubusercontent.com/35340064/50342642-348b0b80-0524-11e9-94ef-c6f4ffa70828.png)

**Comment by naholyr** [comment]
Est-ce que ça ne devrait pas être plutôt "oui" au lieu de "yes" au passage ?

**Comment by naholyr** [comment]
- Corrigé en dév

**Comment by MG95SP** [comment]
Ok en prod
