### ISSUE TITLE
Bugs avec la création d'URL pour chaque centre

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#69]
Lorsqu'on arrive sur la page des centres (http://cartosciencepolitique-pprd.sciences-po.fr/#/centers) il y a un problème avec les flèches à droite qui permettent de déplier les fiches des centres pointent déjà vers le bas comme si ils étaient tous ouverts. 
![image](https://user-images.githubusercontent.com/35340064/50832665-2d9b3000-134f-11e9-807f-50c1b07bc659.png)
Par défaut, les flèches devraient êtres tournées vers la droite. Comme c'est le cas en prod : 
![image](https://user-images.githubusercontent.com/35340064/50832693-40ae0000-134f-11e9-8225-fc2245660955.png)

Après un premier clic sur la flèche d'un centre, l'URL du centre apparaît bien comme prévu : http://cartosciencepolitique-pprd.sciences-po.fr/#/centers/fr2009
Mais la fiche détaillée du centre s'ouvre et se referme instantanément (en laissant l'url spécifique du centre) : 
![image](https://user-images.githubusercontent.com/35340064/50832780-85399b80-134f-11e9-971b-8c65bb3c1e0f.png)

Enfin lorsqu'on clique à nouveau sur la flèche, la fiche détaillé s'ouvre bien, mais cette fois, c'est l'URL spécifique du centre qui a disparu : 
![image](https://user-images.githubusercontent.com/35340064/50832862-ca5dcd80-134f-11e9-87af-34cec303d73a.png)

Il faut donc rétablir l'affichage par défaut avec la flèche vers la droite et que l'URL spécifique d'un centre se s'affiche que lorsque l'on clique sur la flèche pour déplier la fiche détaillée du centre.

**Comment by naholyr** [comment]
C'est corrigé / pushé en dév !

**Comment by MG95SP** [comment]
Le bug est résolu en pprd mais la flèche ne bouge toujours pas. Voir plus haut les 2 premières captures d'écran pprd et prod.

**Comment by MG95SP** [comment]
Ok en prod
