### ISSUE TITLE
Problème avec les champs requis

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#70]
Avec la nouvelle mise à jour du pprd, de nombreux champs pourtant non-obligatoires sont déormais requis dans le formulaire en BO.
Par exemple, un centre TEST pour lequel j'avais rempli l'ensemble des champs requis précédemment me demande désormais 24 champs de plus : "Ce formulaire contient 24 erreur(s) de validation"
L’ensemble des champs ajoutés suite à l'[issue 67](https://github.com/SciencesPoDRIS/CartoScPo/issues/67) (Numero National de Structure ; Lien RNSR ; Fiche du centre dans ScanR ; Wikidata ; Lien Wikipedia ) sont en requis alors que seul le numéro national de structure est censé l'être.
Il y a également des champs sur l'ensemble des autres onglets qui sont passés en champs requis.

Les champs requis sont pourtant normalement très peu nombreux : cf colonne H (required) dans le [CartoScPo - Metadata schema](https://docs.google.com/spreadsheets/d/1WA_jhcnXvJzm6kJsxALKtjXcHpSU7Uh-lsKv6Nes3Jo/edit?usp=sharing).

**Comment by naholyr** [comment]
Pas évident à corriger car je ne reproduis pas ces comportements en local, pour le moment j'ai donc pushé deux choses :

- Le commit 8730072 ajoute la possibilité d'avoir des détails sur les erreurs (incluant la liste complète des erreurs sur les champs ET le contenu de l'objet "center" en cours d'édition), on l'épluchera ensemble pour voir en détail ce qui est bizarre ou non
- Le commit 6c179cf remet en conformité le fichier `schema.json` qui avait encore pas mal d'erreurs (notamment sur la proprieté "required" qui nous intéresse ici)

**Comment by naholyr** [comment]
Ping @jri-sp si tu peux déployer en preprod afin que @MG95SP puisse re-tester dans l'après-midi car pour l'instant on en est toujours à essayer de deviner :/
Il faudrait s'assurer que les images du BO sont bien rebuildés complètement, et le process node bien relancé. Je n'ai pas testé le build "production" en local, je regarde ça maintenant voir si j'arrive à avoir les mêmes comportements.

Parmi les choses "étranges" : 100% des champs semblent required lors de la création d'un nouveau centre, chose que je n'ai pas du tout en local.

**Comment by jri-sp** [comment]
Hello!
C'est en pprd!

**Comment by naholyr** [comment]
Je pense avoir trouvé un build qui fonctionne : *a priori* (à valider après le prochain déploiement pour être sûr que j'ai la bonne solution tout de même) c'était uniquement un problème de dépendance. Une des dépendances du projet a du évoluer dans les 30 derniers jours et comme le Dockerfile ne se base pas sur le "package-lock" il n'a pas récupéré les "bonnes" versions.
Si le fix est bien confirmé, il s'agira d'identifier quelle dépendance est coupable et de la figer dans le "package.json" afin de ne pas se refaire avoir dans le futur. Un "npm update" est vite arrivé et risquerait de ramener ces problèmes.

**Comment by naholyr** [comment]
Ping @jri-sp pour un déploiement en préprod demain si possible, ça devrait être **le bon** :)

**Comment by jri-sp** [comment]
Hello,
C'est déployé

**Comment by naholyr** [comment]
La cause "dépendance" est confirmé, en dév local après un "npm update" je reproduis bien le même comportement. Je vais maintenant procéder dépendance par dépendance pour isoler la fautive.

Merci @jri-sp :)

**Comment by naholyr** [comment]
La dépendance fautive a été isolée, c'est "angular" en toute simplicité :')
La version **1.7.6** est publiée le 17 janvier, et en forçant la **1.7.5** (4 octobre 2018) ça fonctionne à nouveau. Ces équipes étant spécialistes d'introduire des ruptures de compatibilité dans des releases mineures, ça me surprend à moitié mais là c'est carrément dans un patch :/ J'étudie le changelog, et je pusherai la correction qui correspond donc à une modification du numéro de version dans le package.json, et à une éventuelle mise à jour du code.

**Comment by naholyr** [comment]
Afin de rendre tout ça le plus robuste possible, j'ai figé les dépendances après les avoir mises à jour au maximum (tout en respectant les contraintes posées par l'existant). Ça devrait assurer que ce genre d'incident ne se reproduise pas à long terme.

**Comment by naholyr** [comment]
Je pense que le code coupable est identifié : https://github.com/angular/angular.js/issues/16814

**Comment by MG95SP** [comment]
Résolu en pprd !

**Comment by MG95SP** [comment]
Ok en prod
