### ISSUE TITLE
Bug moteur de recherche FO

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#72]
Moteur de recherche ne fonctionne pas sur le FO et ne génère aucun résultat. 
Test avec "ceri" ou "paris" ou "politique" =aucun résultat. Problème sur les champs interrogés ?
Bug existe également en pré-prod
![image](https://user-images.githubusercontent.com/35340064/52077025-47b3e100-2590-11e9-946b-d7ff1416c5ac.png)

**Comment by naholyr** [comment]
Corrigé et pushé en dév, prêt pour la préprod (inclus #62)
