### ISSUE TITLE
Bug d'affichage markdown en FO lors de la création d'un centre

### ISSUE THREAD

**Issue by MG95SP** [SciencesPoDRIS/CartoScPo#73]
Les données saisies en markdown lors de la création d'un centre (CCJ, Chine, Corée, Japon
UMR 8173) s'affichent bien dans la prévisualisation en BO, mais sont illisibles en FO sur les onglets "publications" et "documentation" uniquement.
Affichage en BO : 
![image](https://user-images.githubusercontent.com/35340064/58232106-ee3b1200-7d38-11e9-8bda-94cb0ef1ca9d.png)
Affichage en FO : 
![image](https://user-images.githubusercontent.com/35340064/58232175-25a9be80-7d39-11e9-8e93-c11d0b2b263d.png)

**Comment by MG95SP** [comment]
- centre sur le FO : https://cartosciencepolitique.sciencespo.fr/#/fr/centers/umr8173

- centre BO : https://cartosciencepolitique.sciencespo.fr/bo/centers/umr8173/publications

- exemple saisie markdown pour l'item "Préconisations pour le dépôt en open access des publications" de l'onglet "publications" (celui de la copie d'écran plus haut) : 

Les archives ouvertes des équipes de l'UMR 8173 sont des collections de HAL (Hyper articles en ligne) qui rassemblent les références ou le texte intégral des travaux de chercheurs affiliés à l'EHESS sur la plateforme CCSD (Centre pour la Communication Scientifique Directe).
​
* [Archives ouvertes de l'UMR 8173 Chine, Corée, Japon](https://halshs.archives-ouvertes.fr/UMR-CCJ)
  * [Archives ouvertes du Centre Chine (CECMC)](https://halshs.archives-ouvertes.fr/ACC/?lang=fr)
  * [{Archive ouverte du Centre de Recherches sur la Corée (CRC)](https://halshs.archives-ouvertes.fr/AOCRC/?lang=fr)
  * [Archives ouvertes du Centre de recherche sur le Japon (CRJ)](https://halshs.archives-ouvertes.fr/CRJ)

**Comment by naholyr** [comment]
La cause est identifiée : d'après un message d'erreur en console, dans la base de données au lieu d'avoir ``{"collections": {"enabled":false}}`` on n'a carrément pas la propriété ``collections``, du coup on a une erreur qui bloque le script et les champs suivants ne sont pas convertis.

Je m'occupe de la correction rapidement, il faut que je regarde tout de même :

- pourquoi on a pu avoir des données incomplètes (je m'attendais à ce que l'ORM complète l'objet)
- s'il vaut mieux faire compléter les données par l'API serveur, ou traiter le cas d'un objet incomplet côté client, ou les deux (je m'oriente pour l'instant plus pour traiter l'erreur côté client, afin d'être le plus souple)

**Comment by naholyr** [comment]
La correction est appliquée en dév, commit 3049104

Les deux commits suivant concernent de la mise à jour de versions :
- 2f67de8 mise à jour (non majeures) des dépendances de l'application
- 918f3a9 mise à jour de la version de Node utilisée dans les images Docker pour passer sur la version 10 (Long Term Suppport actuelle)

À valider en preprod avant déploiement en prod

**Comment by MG95SP** [comment]
Pas de changement en pré-prod. le bug reste le même qu'en prod.
le markdown fonctionne bien sur l'onglet "thématique":
![image](https://user-images.githubusercontent.com/35340064/58489784-3b214d00-816c-11e9-96fa-8c818774f0d7.png)
Mais pas sur les onglets "Publications" et "Documentation". De plus, l'item "archivage des données de la recherche" n'apprait pas (en prod et en pprd) alors qu'il est renseigné dans le BO : 
![image](https://user-images.githubusercontent.com/35340064/58490075-c4388400-816c-11e9-8435-6f1dfb1b417e.png)

**Comment by MG95SP** [comment]
Bug résolu. Ok en pprd et en prod.
